version: "3"

services:
  db:
    image: mariadb:10
    container_name: inssa-db-local
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
#      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: INSSA
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_PORT: 3306
      MYSQL_USER: INSSA
      MYSQL_PASSWORD: INSSA
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
  api:
    container_name: inssa-api-local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        PROFILE: local
    ports:
      - 8080:8080
    depends_on:
      - db