version: "3"

services:
  db:
    image: mariadb:10
    container_name: inssa-db-local
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/db/conf.d:/etc/mysql/conf.d
      - ./mariadb/db/initdb.d/init-local.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: ./mariadb/.env
    restart: always

  api:
    container_name: inssa-api-local
    image: amazoncorretto:17-alpine
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/app
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_JDBCURL: jdbc:mariadb://db:3306/inssa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root!
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    working_dir: /usr/app
    depends_on:
      db:
        condition: service_started
    restart: always
