spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbcUrl: jdbc:log4jdbc:mariadb://43.201.175.110:3306/INSSA?serverTimezone=Asia/Seoul
    username: INSSA
    password: INSSA123!@#
#    resource: C:\Users\images
#    resource-path: file
#    upload-path: /upload`

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header:
  secret:
  token-validity-in-seconds: 86400


logging:
  config: classpath:logback-spring.xml
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
