spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/INSSA?serverTimezone=Asia/Seoul
    username: INSSA
    password: INSSA

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: mapper/*.xml

jwt:
  header:
  secret:
  token-validity-in-seconds: 86400

