sns:
  # Google 소셜 로그인 설정
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
    callback:
      url: http://localhost:8080/api/v1/auth/social/google/callback
    token:
      url: https://oauth2.googleapis.com/token

  # Kakao 소셜 로그인 설정
  kakao:
    client:
      id: ${KAKAO_CLIENT_ID}
    redirect:
      uri: http://localhost:8080/api/v1/auth/social/kakao/callback
    authorization:
      grantType: authorization_code
      uri: https://kauth.kakao.com/oauth/authorize
    token:
      uri: https://kauth.kakao.com/oauth/token
    user:
      info:
        uri: https://kapi.kakao.com/v2/user/me

  # Naver 소셜 로그인 설정
  naver:
    client:
      id:
      secret:
    redirect:
      uri: http://localhost:8080/api/v1/auth/social/naver/callback
    authorization:
      grantType: authorization_code
      uri: https://nid.naver.com/oauth2.0/authorize
    token:
      uri: https://nid.naver.com/oauth2.0/token
    user:
      info:
        uri: https://openapi.naver.com/v1/nid/me