spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/INSSA?serverTimezone=Asia/Seoul
    username: INSSA
    password: INSSA
#    resource: C:\Users\images
#    resource-path: file
#    upload-path: /upload


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: mapper/*.xml

jwt:
  header:
  secret:
  token-validity-in-seconds: 86400


logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

