spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbcUrl: jdbc:log4jdbc:mariadb://localhost:3306/INSSA?serverTimezone=Asia/Seoul
    username: INSSA
    password: INSSA
#    resource: C:\Users\images
#    resource-path: file
#    upload-path: /upload


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header:
  secret:
  token-validity-in-seconds: 86400

jpa:
  open-in-view: false
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: update

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

